# Generated by Django 3.1.1 on 2020-09-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor_fornecedoradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FornecedorAdmin',
        ),
    ]
