# Generated by Django 3.1.1 on 2020-09-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_delete_fornecedoradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
